### ISSUE TITLE
DXE-2404 Attempting to rename GTM domain causes TF panic

### ISSUE THREAD

**Issue by hypnotisttom** [akamai/terraform-provider-akamai#393]
### Terraform Version
1.3.1

### Affected Resource(s)
akamai_gtm_domain

### Panic Output
```
akamai_gtm_domain.this[0]: Modifying... [id=<REDACTED>]
╷
│ Error: Plugin did not respond
│ 
│   with akamai_gtm_domain.this[0],
│   on main.tf line 7, in resource "akamai_gtm_domain" "this":
│    7: resource "akamai_gtm_domain" "this" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-akamai plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xdd8b11]

goroutine 48 [running]:
github.com/akamai/terraform-provider-akamai/v3/pkg/providers/gtm.populateDomainObject(0xc01e173cf0?, 0xc01e143b00, {0x1069fe0?, 0xc000559640})
        /Users/mdc/code/github.com/mcalhoun/terraform-provider-akamai/pkg/providers/gtm/resource_akamai_gtm_domain.go:561 +0x291
github.com/akamai/terraform-provider-akamai/v3/pkg/providers/gtm.resourceGTMv1DomainUpdate({0x133acc8, 0xc01e0dcd80}, 0xc01e11c480, {0x1069fe0?, 0xc000559640})
        /Users/mdc/code/github.com/mcalhoun/terraform-provider-akamai/pkg/providers/gtm/resource_akamai_gtm_domain.go:362 +0x5ed
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc00060fa40, {0x133ad00, 0xc01e10d170}, 0xd?, {0x1069fe0, 0xc000559640})
        /Users/mdc/code/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00060fa40, {0x133ad00, 0xc01e10d170}, 0xc01e0e6750, 0xc01e11c300, {0x1069fe0, 0xc000559640})
        /Users/mdc/code/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc015854228, {0x133ac58?, 0xc01e08d000?}, 0xc01e0e9810)
        /Users/mdc/code/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0001661e0, {0x133ad00?, 0xc01e10c990?}, 0xc01e116070)
        /Users/mdc/code/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x110adc0?, 0xc0001661e0}, {0x133ad00, 0xc01e10c990}, 0xc01e0dc3c0, 0x0)
        /Users/mdc/code/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00063a540, {0x133f0b8, 0xc01585a4e0}, 0xc01e0f5b00, 0xc015858480, 0x19a82c0, 0x0)
        /Users/mdc/code/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfe
google.golang.org/grpc.(*Server).handleStream(0xc00063a540, {0x133f0b8, 0xc01585a4e0}, 0xc01e0f5b00, 0x0)
        /Users/mdc/code/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /Users/mdc/code/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/mdc/code/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a

Error: The terraform-provider-akamai plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

exit status 1
```

### Expected Behavior
Not sure if renaming GTM domains is supported by the GTM API; however, what we attempted to do was rename to add the .akadns.net suffix to the domain, as the domain created without it.  I'm surprised the domain created without the .akadns.net suffix.  In an attempt to add the suffix on, this panic resulted.

### Actual Behavior
This TF panic.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a GTM domain (apply the resource)
2. Change its name in the resource (apply again)
3. Panic results

### Note
This is not impacting us.  I simply wanted to send you the crash log, since the TF output recommended we forward it along.  Having said that, if there is no reason to allow a domain without the .akadns.net suffix, I would think either the API or the Provider would want to error out, especially since GTM domains appear to be immutable.

**Comment by kaush-** [comment]
Hi @hypnotisttom,

Thank you for bringing this to our notice. We will keep this page posted on the updates.

Regards,
Piyush

**Comment by lkowalsk-akamai-com** [comment]
@hypnotisttom  
>Not sure if renaming GTM domains is supported by the GTM API;

Once a domain is created, its name cannot be changed. That being said, it should not error out with panic. We will try to fix that.

>however, what we attempted to do was rename to add the .akadns.net suffix to the domain, as the domain created without it. I'm surprised the domain created without the .akadns.net suffix.

Custom domain names is a feature that is not fully rolled out yet, hence it is not working fully as expected. This will still take some time to be fully available.

**Comment by lkowalsk-akamai-com** [comment]
Added gracefull fail for the error instead of panic.
