### ISSUE TITLE
Terraform provider crashes in windows

### ISSUE THREAD

**Issue by vreddhi** [akamai/terraform-provider-akamai#472]
### Terraform Version
```sh
 ../terraform -v
Terraform v1.5.7
on linux_386
+ provider registry.terraform.io/akamai/akamai v5.0.1
```

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    akamai = {
      source  = "akamai/akamai"
      version = "5.0.1"
    }
  }
}

data "akamai_groups" "my-ids" {
}

output "groups" {
  value = data.akamai_groups.my-ids
}
```

### Debug Output
```sh
data.akamai_groups.my-ids: Reading...
╷
│ Error: Request cancelled
│ 
│   with data.akamai_groups.my-ids,
│   on test.tf line 10, in data "akamai_groups" "my-ids":
│   10: data "akamai_groups" "my-ids" {
│ 
│ The plugin.(*GRPCProvider).ReadDataSource request was cancelled.
╵

Stack trace from the terraform-provider-akamai_v5.0.1 plugin:

panic: unaligned 64-bit atomic operation

goroutine 40 [running]:
runtime/internal/atomic.panicUnaligned()
        runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0x1c5c813c, 0x1)
        runtime/internal/atomic/atomic_386.s:125 +0x11
github.com/allegro/bigcache/v2.(*cacheShard).miss(...)
        github.com/allegro/bigcache/v2@v2.2.5/shard.go:398
github.com/allegro/bigcache/v2.(*cacheShard).getWrappedEntry(0x1c5c80b0, 0xad5d310a5390c798)
        github.com/allegro/bigcache/v2@v2.2.5/shard.go:88 +0x10e
github.com/allegro/bigcache/v2.(*cacheShard).get(0x1c5c80b0, {0x203d7700, 0xf}, 0xad5d310a5390c798)
        github.com/allegro/bigcache/v2@v2.2.5/shard.go:64 +0x4a
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1179 +0x3f5
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadDataSource({0x1f650560, 0x1f6505a0, {0x1fd7fe30, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5muxserver/mux_server_ReadDataSource.go:27 +0x151
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0x1fd66320, {0x9181064, 0x203f08d0}, 0x203fa360)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/tf5server/server.go:658 +0x436
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x8f083a0, 0x1fd66320}, {0x9181064, 0x203f08d0}, 0x203f3380, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:455 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0xa4e4480, {0x9183564, 0x1e82c000}, 0x1e668b40, 0x1fd817e8, 0x985e6f8, 0x0)            google.golang.org/grpc@v1.54.0/server.go:1345 +0xed7
google.golang.org/grpc.(*Server).handleStream(0xa4e4480, {0x9183564, 0x1e82c000}, 0x1e668b40, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0xa17google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1        google.golang.org/grpc@v1.54.0/server.go:964 +0x25f

Error: The terraform-provider-akamai_v5.0.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that itcan be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by vreddhi** [comment]
Closing the issue. As the issue was due to wrong binary of terraform.

**Comment by vreddhi** [comment]
Closing the issue. As the issue was due to wrong binary of terraform.

**Comment by vreddhi** [comment]
Closing the issue. As the issue was due to wrong binary of terraform.
