### ISSUE TITLE
Issue: Running an example fails with error

### ISSUE THREAD

**Issue by dcherniv** [akamai/terraform-provider-akamai#7]
### Terraform Version
Terraform v0.11.3
+ provider.akamai (unversioned)

### Affected Resource(s)
akamai_property

### Terraform Configuration Files
```hcl
provider "akamai" {
   edgerc = "/home/dchernivetsky/.edgerc"
   papi_section = "papi"
}

resource "akamai_property" "property01" {
  account_id = "act_1-5KDNQ"
  contract_id = "ctr_3-G97WAR"
  product_id = "prd_SPM"
  group_id   = "grp_114016" 
  cp_code    = "669473"
  name = "worldtour"
  contact = [ "dcherniv@gmail.com"]
  hostname = ["terraform.jetblue.com"]
  network = "staging"
  rules {
    rule {
      name = "l10n"
      comment = "Localize the default timezone"
      criteria {
        name = "path"
        option {
          key = "matchOperator"
          value = "MATCHES_ONE_OF"
        }
        option {
          key = "matchCaseSensitive"
          value = "true"
        }
        option {
          key = "values"
          values = ["/"]
        }
      }
      behavior {
        name = "rewriteUrl"
        option {
          key = "behavior"
          value = "REWRITE"
        }
        option {
          key = "behavior"
          value = "REWRITE"
        }
        option {
          key = "targetUrl"
          value = "/America/Los_Angeles"
        }
      }
    }
  }
}
```

### Debug Output
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
akamai_property.property01: Modifying... (ID: prp_438999)
  activate:                                                                                 "" => "true"
  contact.#:                                                                                "0" => "1"
  contact.1752627656:                                                                       "" => "dcherniv@gmail.com"
  hostname.#:                                                                               "0" => "1"
  hostname.890848451:                                                                       "" => "terraform.jetblue.com"
  network:                                                                                  "" => "staging"
  product_id:                                                                               "" => "prd_SPM"
  rules.#:                                                                                  "0" => "1"
  rules.3966336199.behavior.#:                                                              "0" => "0"
  rules.3966336199.criteria_match:                                                          "" => "all"
  rules.3966336199.rule.#:                                                                  "0" => "1"
  rules.3966336199.rule.2041842398.behavior.#:                                              "0" => "1"
  rules.3966336199.rule.2041842398.behavior.1476367883.name:                                "" => "rewriteUrl"
  rules.3966336199.rule.2041842398.behavior.1476367883.option.#:                            "0" => "2"
  rules.3966336199.rule.2041842398.behavior.1476367883.option.3619073559.key:               "" => "targetUrl"
  rules.3966336199.rule.2041842398.behavior.1476367883.option.3619073559.value:             "" => "/America/Los_Angeles"
  rules.3966336199.rule.2041842398.behavior.1476367883.option.3619073559.values.#:          "0" => "0"
  rules.3966336199.rule.2041842398.behavior.1476367883.option.4186327309.key:               "" => "behavior"
  rules.3966336199.rule.2041842398.behavior.1476367883.option.4186327309.value:             "" => "REWRITE"
  rules.3966336199.rule.2041842398.behavior.1476367883.option.4186327309.values.#:          "0" => "0"
  rules.3966336199.rule.2041842398.comment:                                                 "" => "Localize the default timezone"
  rules.3966336199.rule.2041842398.criteria.#:                                              "0" => "1"
  rules.3966336199.rule.2041842398.criteria.1795066548.name:                                "" => "path"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.#:                            "0" => "3"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.1144384654.key:               "" => "values"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.1144384654.value:             "" => ""
  rules.3966336199.rule.2041842398.criteria.1795066548.option.1144384654.values.#:          "0" => "1"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.1144384654.values.3805201334: "" => "/"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.2909892246.key:               "" => "matchCaseSensitive"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.2909892246.value:             "" => "true"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.2909892246.values.#:          "0" => "0"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.3650817812.key:               "" => "matchOperator"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.3650817812.value:             "" => "MATCHES_ONE_OF"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.3650817812.values.#:          "0" => "0"
  rules.3966336199.rule.2041842398.criteria_match:                                          "" => "all"
  rules.3966336199.rule.2041842398.name:                                                    "" => "l10n"
  rules.3966336199.rule.2041842398.rule.#:                                                  "0" => "0"
  rules.3966336199.variable.#:                                                              "0" => "0"
akamai_property.property01: Still modifying... (ID: prp_438999, 10s elapsed)
Error: Error applying plan:

1 error(s) occurred:

* akamai_property.property01: 1 error(s) occurred:

* akamai_property.property01: Error - Invalid Property Rules
 Rule validation error: https://problems.luna.akamaiapis.net/papi/v0/validation/generic_behavior_issue.invalid_custom_override  Invalid Custom Override: .  

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Should have updated the property.

### Actual Behavior
Didn't update the property and actually probably broke it, because i cannot access the property in luna control center anymore

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
none

### References
none

**Comment by dcherniv** [comment]
@dshafik 
Some more information. The property was created through luna control center then terraform imported, pretty much followed the example in the akamai devops handbook.
I noticed that there is a custom override in the luna control center. 
![image](https://user-images.githubusercontent.com/19437418/35983657-77bdab7c-0cc0-11e8-8748-284882fd3ae0.png)
When i delete that custom override in luna, and run terraform apply it comes back and terraform chokes.

So the problem is either in the config that terraform imported or somehow a "blank" custom override sneaks in when creating a property through terraform. But i dont see any in the plan:
```
akamai_property.property01: Modifying... (ID: prp_438999)
  activate:                                                                                 "" => "true"
  contact.#:                                                                                "0" => "1"
  contact.1752627656:                                                                       "" => "dcherniv@gmail.com"
  hostname.#:                                                                               "0" => "1"
  hostname.2010526249:                                                                      "" => "dev.b6prdeng.net"
  network:                                                                                  "" => "staging"
  product_id:                                                                               "" => "prd_SPM"
  rules.#:                                                                                  "0" => "1"
  rules.3966336199.behavior.#:                                                              "0" => "0"
  rules.3966336199.criteria_match:                                                          "" => "all"
  rules.3966336199.rule.#:                                                                  "0" => "1"
  rules.3966336199.rule.2041842398.behavior.#:                                              "0" => "1"
  rules.3966336199.rule.2041842398.behavior.1476367883.name:                                "" => "rewriteUrl"
  rules.3966336199.rule.2041842398.behavior.1476367883.option.#:                            "0" => "2"
  rules.3966336199.rule.2041842398.behavior.1476367883.option.3619073559.key:               "" => "targetUrl"
  rules.3966336199.rule.2041842398.behavior.1476367883.option.3619073559.value:             "" => "/America/Los_Angeles"
  rules.3966336199.rule.2041842398.behavior.1476367883.option.3619073559.values.#:          "0" => "0"
  rules.3966336199.rule.2041842398.behavior.1476367883.option.4186327309.key:               "" => "behavior"
  rules.3966336199.rule.2041842398.behavior.1476367883.option.4186327309.value:             "" => "REWRITE"
  rules.3966336199.rule.2041842398.behavior.1476367883.option.4186327309.values.#:          "0" => "0"
  rules.3966336199.rule.2041842398.comment:                                                 "" => "Localize the default timezone"
  rules.3966336199.rule.2041842398.criteria.#:                                              "0" => "1"
  rules.3966336199.rule.2041842398.criteria.1795066548.name:                                "" => "path"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.#:                            "0" => "3"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.1144384654.key:               "" => "values"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.1144384654.value:             "" => ""
  rules.3966336199.rule.2041842398.criteria.1795066548.option.1144384654.values.#:          "0" => "1"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.1144384654.values.3805201334: "" => "/"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.2909892246.key:               "" => "matchCaseSensitive"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.2909892246.value:             "" => "true"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.2909892246.values.#:          "0" => "0"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.3650817812.key:               "" => "matchOperator"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.3650817812.value:             "" => "MATCHES_ONE_OF"
  rules.3966336199.rule.2041842398.criteria.1795066548.option.3650817812.values.#:          "0" => "0"
  rules.3966336199.rule.2041842398.criteria_match:                                          "" => "all"
  rules.3966336199.rule.2041842398.name:                                                    "" => "l10n"
  rules.3966336199.rule.2041842398.rule.#:                                                  "0" => "0"
  rules.3966336199.variable.#:                                                              "0" => "0"
```

Hope it makes it clearer.

**Comment by dcherniv** [comment]
Hack around the issue attached.
```
--- rules.go	2018-02-08 16:50:36.000000000 -0500
+++ rulesnew.go	2018-02-08 16:51:05.000000000 -0500
@@ -207,10 +207,10 @@
 		IsSecure bool `json:"is_secure,omitempty"`
 	} `json:"options,omitempty"`
 
-	CustomOverride struct {
-		Name       string `json:"name"`
-		OverrideID string `json:"overrideId"`
-	} `json:"customOverride,omitempty"`
+	//CustomOverride struct {
+//		Name       string `json:"name"`
+//		OverrideID string `json:"overrideId"`
+//	} `json:"customOverride,omitempty"`
 }
 
 // NewRule creates a new Rule
```

**Comment by dshafik** [comment]
@dcherniv that will work if you're not using `customOverride`'s, I will have a proper fix for this over the next couple of days

**Comment by partamonov** [comment]
For me creation of property fails with panic

terraform version: `0.11.3`

Configuration
```
provider "akamai" {
  edgerc = "~/.edgerc"
  papi_section = "default"
}

resource "akamai_property" "sandbox" {
  activate = false
  network = "STAGING"

	name = "sandbox.akamaideveloper.com"
  group_id = "grp_XXXXX"
  account_id = "0000000"
  contract_id = "ctr_XXXXXXX"
	contact = ["contact.com"]
	hostname = ["sandbox.akamaideveloper.com"]
  cp_code = "XXXXXXX"

	rules {...
```

```
2018-02-09T10:54:51.176+0100 [DEBUG] plugin.terraform-provider-akamai: 2018/02/09 10:54:51 [DEBUG] Fetching groups
2018-02-09T10:54:53.406+0100 [DEBUG] plugin.terraform-provider-akamai: 2018/02/09 10:54:53 [DEBUG] Group found: XXXXXX
2018-02-09T10:54:53.406+0100 [DEBUG] plugin.terraform-provider-akamai: 2018/02/09 10:54:53 [DEBUG] Fetching contract
2018-02-09T10:54:53.716+0100 [DEBUG] plugin.terraform-provider-akamai: 2018/02/09 10:54:53 [DEBUG] Contract found: XXXXXXX
2018-02-09T10:54:53.716+0100 [DEBUG] plugin.terraform-provider-akamai: 2018/02/09 10:54:53 [DEBUG] Fetching product
2018-02-09T10:54:53.716+0100 [DEBUG] plugin.terraform-provider-akamai: 2018/02/09 10:54:53 [DEBUG] Setting up clone from
2018/02/09 10:54:56 [TRACE] dag/walk: vertex "provider.akamai (close)", waiting for: "akamai_property.sandbox"
2018/02/09 10:54:56 [TRACE] dag/walk: vertex "root", waiting for: "meta.count-boundary (count boundary fixup)"
2018/02/09 10:54:56 [TRACE] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "akamai_property.sandbox"
2018-02-09T10:54:59.384+0100 [DEBUG] plugin.terraform-provider-akamai: 2018/02/09 10:54:59 [DEBUG] Creating property
2018-02-09T10:54:59.386+0100 [DEBUG] plugin.terraform-provider-akamai: panic: runtime error: invalid memory address or nil pointer dereference
2018-02-09T10:54:59.386+0100 [DEBUG] plugin.terraform-provider-akamai: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1856be5]
2018-02-09T10:54:59.386+0100 [DEBUG] plugin.terraform-provider-akamai:
2018-02-09T10:54:59.386+0100 [DEBUG] plugin.terraform-provider-akamai: goroutine 73 [running]:
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai: github.com/terraform-providers/terraform-provider-akamai/akamai.createProperty(0xc420350750, 0xc42005e420, 0x0, 0x0, 0xc4203401c0, 0x90, 0xc420368c18, 0x1009d93)
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai:  /Users/partamonov/go/src/github.com/terraform-providers/terraform-provider-akamai/akamai/resource_akamai_property_create.go:174 +0x1b5
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai: github.com/terraform-providers/terraform-provider-akamai/akamai.resourcePropertyCreate(0xc4203401c0, 0x18d28e0, 0x206ea50, 0x24, 0x206fce0)
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai:  /Users/partamonov/go/src/github.com/terraform-providers/terraform-provider-akamai/akamai/resource_akamai_property_create.go:60 +0x1100
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc420218380, 0xc4204e40a0, 0xc420344d40, 0x18d28e0, 0x206ea50, 0x1, 0xc4203e2210, 0xc4203e2210)
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai:  /Users/partamonov/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:227 +0x364
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4202183f0, 0xc4204e4000, 0xc4204e40a0, 0xc420344d40, 0x2289000, 0x0, 0x18)
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai:  /Users/partamonov/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa4
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc420228f20, 0xc420344020, 0xc420346640, 0x0, 0x0)
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai:  /Users/partamonov/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai: reflect.Value.call(0xc420302900, 0xc4203f0460, 0x13, 0x1a654c5, 0x4, 0xc42003df20, 0x3, 0x3, 0x0, 0x0, ...)
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai:  /usr/local/Cellar/go/1.9.3/libexec/src/reflect/value.go:434 +0x905
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai: reflect.Value.Call(0xc420302900, 0xc4203f0460, 0x13, 0xc42002af20, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai:  /usr/local/Cellar/go/1.9.3/libexec/src/reflect/value.go:302 +0xa4
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai: net/rpc.(*service).call(0xc42031f400, 0xc4203ee960, 0xc4200190d8, 0xc420377680, 0xc42037d880, 0x18cc7e0, 0xc420344020, 0x16, 0x18cc820, 0xc420346640, ...)
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai:  /usr/local/Cellar/go/1.9.3/libexec/src/net/rpc/server.go:381 +0x142
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai: created by net/rpc.(*Server).ServeCodec
2018-02-09T10:54:59.387+0100 [DEBUG] plugin.terraform-provider-akamai:  /usr/local/Cellar/go/1.9.3/libexec/src/net/rpc/server.go:475 +0x36b
2018/02/09 10:54:59 [TRACE] root: eval: *terraform.EvalWriteState
2018/02/09 10:54:59 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2018/02/09 10:54:59 [TRACE] root: eval: *terraform.EvalIf
2018/02/09 10:54:59 [TRACE] root: eval: *terraform.EvalWriteState
2018/02/09 10:54:59 [TRACE] root: eval: *terraform.EvalWriteDiff
2018/02/09 10:54:59 [TRACE] root: eval: *terraform.EvalApplyPost
2018/02/09 10:54:59 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* akamai_property.sandbox: unexpected EOF
2018/02/09 10:54:59 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* akamai_property.sandbox: unexpected EOF
2018/02/09 10:54:59 [TRACE] [walkApply] Exiting eval tree: akamai_property.sandbox
2018/02/09 10:54:59 [TRACE] dag/walk: upstream errored, not walking "provider.akamai (close)"
2018/02/09 10:54:59 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2018/02/09 10:54:59 [TRACE] dag/walk: upstream errored, not walking "root"
2018/02/09 10:54:59 [TRACE] Preserving existing state lineage "b94bf901-55ef-4cc1-adf0-4f5f2ea55033"
2018/02/09 10:54:59 [TRACE] Preserving existing state lineage "b94bf901-55ef-4cc1-adf0-4f5f2ea55033"
2018/02/09 10:54:59 [TRACE] Preserving existing state lineage "b94bf901-55ef-4cc1-adf0-4f5f2ea55033"
2018/02/09 10:54:59 [TRACE] Preserving existing state lineage "b94bf901-55ef-4cc1-adf0-4f5f2ea55033"
2018-02-09T10:54:59.393+0100 [DEBUG] plugin: plugin process exited: path=/Users/partamonov/repos/ing_repos/terraform/akamai/terraform-provider-akamai
2018/02/09 10:54:59 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-02-09T10:54:59.397+0100 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
```

**Comment by dshafik** [comment]
@partamonov can you try with this latest version?
